# This file has been generated by node2nix 1.11.1. Do not edit!
{
  lib,
  stdenv,
  fetchurl,
  nix-gitignore,
  fetchgit,
  fetchFromGitHub,
  nodejs ? nodejs_18,
  nodejs_18,
  python2,
  runCommand,
  writeTextFile,
  writeShellScript,
  darwin,
}: let
  nodeEnv = import ./node-env.nix {
    inherit stdenv lib python2 runCommand writeTextFile writeShellScript nodejs;
    pkgs = { inherit stdenv lib python2 runCommand writeTextFile writeShellScript nodejs darwin fetchurl nix-gitignore fetchgit fetchFromGitHub; };
    libtool =
      if stdenv.isDarwin
      then darwin.cctools
      else null;
  };
in
  import ./node-packages.nix {
    inherit fetchurl nix-gitignore stdenv lib fetchgit fetchFromGitHub nodeEnv;
  }
