# Boot configuration for OCI (Oracle Cloud Infrastructure)
#
# Filesystem mounts are auto-generated by nixos-generate-config.
# This file only contains boot loader and btrfs settings.
# NO DISKO - it causes OOM on 1GB RAM instances.
{ config, pkgs, lib, ... }:

{
  # Boot loader - UEFI with systemd-boot
  boot.loader = {
    systemd-boot.enable = true;
    systemd-boot.configurationLimit = 5;
    efi.canTouchEfiVariables = true;
    efi.efiSysMountPoint = "/boot";
  };

  # BTRFS support
  boot.supportedFilesystems = [ "btrfs" ];

  services.btrfs.autoScrub = {
    enable = true;
    interval = "monthly";
    fileSystems = [ "/" ];
  };

  environment.systemPackages = with pkgs; [
    btrfs-progs
  ];
}
