{ config, lib, pkgs, ... }:

let
  # Machine-specific bar height (eww bar)
  barHeight = if config.networking.hostName == "asahi" then 40 else 36;

  # Golden ratio dimensions for dropdown terminal
  # Width: 61.8% of screen, centered (19.1% from each side)
  # Height: 61.8% of screen height
  dropdownWidth = "61.8%";
  dropdownHeight = "61.8%";
  dropdownX = "19.1%";  # (100 - 61.8) / 2 = 19.1
in {
  # Generate machine-specific Hyprland variables
  home-manager.users.andrei = { pkgs, ... }: {
    xdg.configFile."hypr/vars.conf".text = ''
      # Machine-specific Hyprland variables
      # Generated by NixOS for ${config.networking.hostName}
      $mainMod = SUPER
      $barHeight = ${toString barHeight}
    '';

    # Dropdown window rules (machine-specific due to bar height)
    xdg.configFile."hypr/dropdown.conf".text = ''
      # Dropdown terminal window rules
      # Generated by NixOS for ${config.networking.hostName}
      # Golden ratio sizing (61.8% width and height)

      # Assign to special workspace FIRST (before other rules)
      windowrulev2 = workspace special:dropdown silent, class:^(dropdown)$

      # Float the dropdown window
      windowrulev2 = float, class:^(dropdown)$

      # Golden ratio size (61.8% width and height)
      windowrulev2 = size ${dropdownWidth} ${dropdownHeight}, class:^(dropdown)$

      # Center horizontally, position one bar height below the bar (${toString barHeight}*2 = ${toString (barHeight * 2)}px)
      windowrulev2 = move ${dropdownX} ${toString (barHeight * 2)}, class:^(dropdown)$

      # Visual styling
      windowrulev2 = dimaround, class:^(dropdown)$
    '';
  };
}
