{ config, lib, pkgs, ... }:

let
  # Machine-specific settings (riva is the Asahi machine)
  isAsahi = config.networking.hostName == "riva";

  # Bar height (waybar) - in pixels, fixed per machine
  barHeight = if isAsahi then 40 else 36;
in {
  # Generate machine-specific Hyprland variables
  home-manager.users.andrei = { pkgs, config, ... }: {
    xdg.configFile."hypr/vars.conf".text = ''
      # Machine-specific Hyprland variables
      # Generated by NixOS for ${config.networking.hostName or "unknown"}
      $mainMod = SUPER
      $barHeight = ${toString barHeight}
    '';

    # Dropdown settings - mutable symlink to repo file
    # Edit the file directly and run `hyprctl reload` to test changes
    xdg.configFile."hypr/dropdown.conf".source =
      config.lib.file.mkOutOfStoreSymlink "/home/andrei/dev/nixos-config/linux/hyprland/dropdown-settings.conf";
  };
}
