{ config, lib, pkgs, ... }:

let
  ui = import ../../shared/ui.nix;

  # Machine-specific settings (riva is the Asahi machine)
  isAsahi = config.networking.hostName == "riva";

  # Monitor config (riva: native P3 color management, vibrance via screen shader)
  monitorConfig = ''
    monitor=eDP-1,preferred,auto,1.6${if isAsahi then ",cm,dp3" else ""}
  '' + (if !isAsahi then ''
    monitor=,preferred,auto,1.875
  '' else "");
in {
  # Generate machine-specific Hyprland variables
  home-manager.users.andrei = { pkgs, config, ... }: {
    xdg.configFile."hypr/vars.conf".text = ''
      # Machine-specific Hyprland variables
      # Generated by NixOS for ${config.networking.hostName or "unknown"}
      $mainMod = SUPER
      $fontFamily = ${ui.fontFamily}
      $fontSizePt = ${toString ui.fontSizePt}

      # Monitor configuration
      ${monitorConfig}
    '';

    # Dropdown settings - mutable symlink to repo file
    # Edit the file directly and run `hyprctl reload` to test changes
    xdg.configFile."hypr/dropdown.conf".source =
      config.lib.file.mkOutOfStoreSymlink "/home/andrei/dev/nixos-config/linux/hyprland/dropdown-settings.conf";
  };
}
