keys:
  - &personal age10q9h5a7eml9s4x9mqd64srw7u6us6zamhajjgp4nemfqe6tc5s0q4vvfs0
  - &mac age1tljrrk6stmraanxcn580j75vxfrp4d8qpwdc9m4wyhwaght6eguqza0qt0
  - &riva age1qanq2pe3zrf5jxl8c3yctjx0yjd8z6jrcnzell45mfhvfdwc7q8qua5zvv
  - &watts age19g7fqq7ux6dfk9ncf2rkn3glkm4pxueye8md32r9hqe2fraw5qtsxxzt38

creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *personal
          - *mac
          - *riva
          - *watts
