flags: {}
nix:
  packages:
  - alsaLib
  - cairo
  - gnome2.pango
  - gtk2-x11
  - libxml2
  - pkgconfig
  - upower
  - wirelesstools
  - x11
  - xorg.libX11
  - xorg.libXext
  - xorg.libXinerama
  - xorg.libXpm
  - xorg.libXrandr
  - xorg.libXrender
  - xorg.xmessage
  - gcc
  enable: true
  pure: true
packages:
- .
extra-deps: []
resolver: lts-11.4
