#!/usr/bin/env ruby

require 'json'

def get_focused_workspace
  workspaces = JSON.parse(`swaymsg -t get_workspaces`)
  workspaces.find { |ws| ws['focused'] }['name']
end

def get_window_count(workspace)
  tree = JSON.parse(`swaymsg -t get_tree`)
  nodes = tree.dig('nodes').find { |node| node['type'] == 'workspace' && node['name'] == workspace }&.dig('nodes')
  nodes&.count { |node| node['type'] == 'con' } || 0
end

def set_border(workspace, border)
  `swaymsg "[workspace=#{workspace}] border #{border}"`
end

IO.popen('swaymsg -m -t subscribe \'["window"]\'').each_line do |event|
  event_data = JSON.parse(event)
  next unless event_data['change'] == 'new' || event_data['change'] == 'close'

  focused_workspace = get_focused_workspace
  window_count = get_window_count(focused_workspace)

  set_border focused_workspace, window_count == 1 ? 'none' : normal
end
