{pkgs, ...}: let
  cursor-theme = "Adwaita";
  cursor-size = 48;
in {
  home-manager.users.andrei = {
    home.packages = [pkgs.adwaita-icon-theme];

    home.sessionVariables = {
      XCURSOR_THEME = cursor-theme;
      XCURSOR_SIZE = cursor-size;
    };

    gtk.cursorTheme.name = cursor-theme;
    gtk.cursorTheme.size = cursor-size;

    xdg.configFile."hypr/cursor.conf".text = ''
      # Cursor configuration - generated by NixOS
      env = XCURSOR_THEME,${cursor-theme}
      env = XCURSOR_SIZE,${toString cursor-size}
      env = HYPRCURSOR_THEME,${cursor-theme}
      env = HYPRCURSOR_SIZE,${toString cursor-size}
    '';
  };
}
