#!/usr/bin/env zsh

while id=$(makoctl list | jq '.data | first | select(.[]."app-name".data == "Spotify") | first | .id.data'); do
  [ -z $id ] \
    && sleep 1 \
    || { sleep 10 && makoctl dismiss -n $id };
done
