{ config, lib, pkgs, ... }:

let
  # Machine-specific settings
  isAsahi = config.networking.hostName == "asahi";

  # Bar height for notch support on Asahi
  barHeight = if isAsahi then 40 else 36;
in
{
  # EWW bar systemd user service
  home-manager.users.andrei = { config, pkgs, ... }: {
    # Generate machine-specific eww bar height configuration
    xdg.configFile."eww/bar-config.yuck".text = ''
      ; Machine-specific bar configuration
      ; Generated by NixOS

      ; Bar height - optimized for notch on Asahi (40px) vs standard (36px)
      (defvar bar-height ${toString barHeight})
    '';

    systemd.user.services.eww = {
      Unit = {
        Description = "ElKowars wacky widgets daemon";
        PartOf = [ "graphical-session.target" ];
        After = [ "graphical-session.target" ];
      };
      Service = {
        Type = "simple";
        ExecStart = "${pkgs.eww}/bin/eww daemon --no-daemonize";
        ExecStartPost = "${pkgs.eww}/bin/eww open bar";
        Restart = "on-failure";
      };
      Install.WantedBy = [ "graphical-session.target" ];
    };

    # Hyprland listener for eww workspace updates
    systemd.user.services.eww-hyprland-listener = {
      Unit = {
        Description = "EWW Hyprland workspace listener";
        PartOf = [ "graphical-session.target" ];
        After = [ "graphical-session.target" "eww.service" ];
        Requires = [ "eww.service" ];
      };
      Service = {
        Type = "simple";
        ExecStart = "%h/.config/eww/scripts/hyprland-listener";
        Restart = "on-failure";
      };
      Install.WantedBy = [ "graphical-session.target" ];
    };
  };
}
