pkgs:
with pkgs;
  [
    acpi
    eww
    grim
    hyprsunset
    lan-mouse  # Wayland-native keyboard/mouse sharing (both machines Linux)
    waynergy  # Wayland-native Synergy client (if server is Mac/Windows with Synergy license)
    kitty
    slurp
    wf-recorder
    ydotool
    alsa-utils
    beeper
    binutils
    caprine-bin
    detox
    ffmpeg-full
    fswebcam
    gcolor3
    gnome-epub-thumbnailer
    imv
    inotify-tools
    iotop
    libnotify
    libreoffice-fresh
    libsForQt5.breeze-gtk
    libsForQt5.breeze-qt5
    libsForQt5.kdegraphics-thumbnailers
    lm_sensors
    lshw
    nethogs
    osquery
    pciutils
    playerctl
    psmisc
    puppeteer-cli
    slack
    strace
    sublime4
    swaytools
    tidal-hifi
    trash-cli
    usbutils
    whatsapp-for-linux
    wlprop
    xdg-user-dirs
    xdragon
    ytmdesktop
    emacs
  ]
