pkgs:
with pkgs;
  [
    acpi
    alsa-utils
    beeper
    binutils
    libsForQt5.breeze-qt5
    caprine-bin
    detox
    ffmpeg-full
    fswebcam
    gcolor3
    gnome-epub-thumbnailer
    imv
    inotify-tools
    iotop
    libnotify
    libreoffice-fresh
    libsForQt5.breeze-gtk
    libsForQt5.kdegraphics-thumbnailers
    lm_sensors
    lshw
    mpv
    nethogs
    pciutils
    playerctl
    psmisc
    puppeteer-cli
    slack
    strace
    sublime4
    swaytools
    telegram-desktop
    tidal-hifi
    trash-cli
    usbutils
    whatsapp-for-linux
    wlprop
    xdg-user-dirs
    xdragon
    ytmdesktop
    zoom-us
  ]
